### ISSUE TITLE
VLAN on host pNIC?

### ISSUE THREAD

**Issue by JamesKehr** [microsoft/Validate-DCB#32]
This test starting on line 256 of global.unit.tests.ps1.

`                    ### Verify each VMSwitch.RDMAEnabledAdapter includes the VLANID property from Get-NetAdapterAdvancedProperty
                    It "[Config File]-[AllNodes.VMSwitch.RDMAEnabledAdapters]-[Node: $($thisNode.NodeName)]-[Entry: $($thisRDMAEnabledAdapter.Name)]-[Noun: NetAdapterAdvancedProperty] Must include the VLANID property for each entry" {
                        $thisRDMAEnabledAdapter.VLANID | Should not BeNullOrEmpty
                    }`

Based on the example config files this is checking the pNIC for a VLANID. But shouldn't the pNIC be in TRUNK mode?

Based on this example:

`                RDMAEnabledAdapters = @(
                    @{ Name = 'RoCE-01'  ; VMNetworkAdapter = 'SMB01' ; VLANID = '101' ; JumboPacket = 9014 }
                    @{ Name = 'RoCE-02'  ; VMNetworkAdapter = 'SMB02' ; VLANID = '101' ; JumboPacket = 9014 }
                )`

The test runs against RoCE-1, which is the pNIC. The VLAN test should be run against the affinitized VMNetworkAdapter, SMB*.

**Comment by dcuomo** [comment]
Hi @JamesKehr - Since this is a global test, it's merely validating that the configuration file is properly created. In this instance, each entry (including a pNIC and vNIC since this is under the VMSwitch hierarchy) must have a VLAN specified. In the modal tests, Validate-DCB will ensure that the host vNIC has the specified VLAN, and the pNIC is set to 0.

I think this answers the question in that the confusion is that this is in global and checking the configuration file for errors. If resolved, please close the issue.

**Comment by dcuomo** [comment]
Note: The confusion could be that the ### Verify is a bit misleading. Feel free to propose a PR that fixes that to be more explicit about validation of the config file.

**Comment by JamesKehr** [comment]
Basically the pNIC VLAN value must always be set to 0 when it is attached to a vmSwitch/SET in the config file. For validation type stuff.
