### ISSUE TITLE
Add BIOS settings verification

### ISSUE THREAD

**Issue by otero16** [microsoft/Validate-DCB#46]
Hello,

I have seen that the script does not include checking the settings on the BIOS settings, this can lead to situations that following the steps and the script is not reporting any errors still DCB is not enabled.

Can you please include BIOS settings verifications, on the image we have one example of this from DELL BIOS settings.

![DCBX DELL Example](https://user-images.githubusercontent.com/59911517/101135020-817e2480-360b-11eb-9ade-53d013ec5682.png)

**Comment by dcuomo** [comment]
Hi @otero16 - I'm not sure how to tackle this with inbox capabilities. Do you have a suggestion? Is there perhaps an extra helper module that could be layered on top of this to cover various vendors (e.g. Dell, Lenovo, HPE, etc.?)?

**Comment by dcuomo** [comment]
While this isn't ideal, a failing system won't be passed through if the bios settings are not correct. The system will either support the wrong type of RDMA or will show as not operational in SMB.

Considering the above, and the fact we have not received any additional ideas (or comments since January), closing this for now.
